- hosts: ciweb
  connection: smart
  gather_facts: false
  tasks:
  - name: Nuke it if it exists
    shell: rm -rf {{ ref_name }}*
    args:
      chdir: ~/www/solidfire-ci-logs

  - name: Create ref directory on web server
    shell: mkdir ~/www/solidfire-ci-logs/{{ ref_name }}

  - name: Copy backup of console file
    copy: src={{ results_dir }}/console.log.out dest=~/www/solidfire-ci-logs/{{ ref_name }}/console.log.out
    ignore_errors: yes

  - name: Copy ansible logs to web-server
    copy: src={{ results_dir }}/{{ item }} dest=~/www/solidfire-ci-logs/{{ ref_name }}
    ignore_errors: yes
    with_items:
      - ansible.out

  - name: Copy files to web server
    copy: src={{ results_dir }}/{{ item }} dest=~/www/solidfire-ci-logs/{{ ref_name }}
    ignore_errors: yes
    with_items:
      - stack.sh.log.out
      - "{{ ref_name }}.tar.gz"

  - name: Untar log files on web
    shell: tar -xzf {{ ref_name }}.tar.gz
    ignore_errors: yes
    args:
      chdir: ~/www/solidfire-ci-logs/{{ ref_name }}

